server:
  port: 8080

spring:
  application:
    name: training-backend
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/training.db

codeforces:
  base_url: https://codeforces.com/api
