server:
  port: 8080

spring:
  application:
    name: training-backend
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:/Users/29768/Desktop/whut-training-team/backend/data/training.db

codeforces:
  base_url: https://codeforces.com/api

app:
  logging:
    service:
      enabled: true
  auth:
    access-token-ttl-seconds: 1800
    refresh-token-ttl-seconds: 604800
  daily-problem:
    min-rating: 1200
    max-rating: 2000
    no-repeat-days: 90
    cron: "0 5 0 * * *"
    sync-cron: "0 0 0 * * MON"
    zone: "Asia/Shanghai"

logging:
  level:
    com.whut.training.interceptor.RequestLoggingInterceptor: INFO
    com.whut.training.aspect.logging.ServiceLogAspect: INFO
